import { ZodiacSignInfo } from '../types';

export type RelationshipStatus = 'single' | 'dating' | 'married';

export interface LoveCategoryForecast {
  title: string;
  status: RelationshipStatus;
  headline: string;
  overview: string;
  cosmicVibe: string;
  heartRating: number; // 1 to 5
  keyGuidance: string;
  greenFlagOrFocus: string;
  sacredAction: string;
  bestMatches: string[];
  intimacyTip: string;
}

export const getLoveRelationshipForecast = (
  sign: ZodiacSignInfo,
  status: RelationshipStatus,
  period: 'today' | 'tomorrow' | 'weekly' | 'monthly' = 'today'
): LoveCategoryForecast => {
  const signName = sign.name.toLowerCase();

  const forecasts: Record<string, Record<RelationshipStatus, Omit<LoveCategoryForecast, 'status' | 'title'>>> = {
    aries: {
      single: {
        headline: 'Bold Charisma & Spontaneous Allure',
        overview: 'Mars ignites your magnetic presence. You are radiating raw authenticity and courageous confidence that naturally draws curious admirers into your energetic orbit.',
        cosmicVibe: 'Electrifying & Independent',
        heartRating: 5,
        keyGuidance: 'Do not chase; let your vibrant enthusiasm be the cosmic beacon. Your ideal connection respects your autonomy.',
        greenFlagOrFocus: 'Someone who cheers on your passions and matches your quick wit without intimidation.',
        sacredAction: 'Wear a bold crimson accent or carry carnelian to amplify your romantic aura.',
        bestMatches: ['Leo', 'Sagittarius', 'Gemini'],
        intimacyTip: 'Initiate playful banter—honest, direct eye contact is your secret romantic superpower.',
      },
      dating: {
        headline: 'Spirited Chemistry & Thrilling Adventures',
        overview: 'Your dating dynamic thrives on spontaneity and momentum. Today invites playful competition and unfiltered laughter with someone who keeps you on your toes.',
        cosmicVibe: 'Playful Fire & Dynamic Banter',
        heartRating: 4,
        keyGuidance: 'Balance your fiery initiative with active listening. Leave room for mystery to unfold naturally.',
        greenFlagOrFocus: 'Consistent follow-through and enthusiastic participation in joint spontaneous plans.',
        sacredAction: 'Plan a date centered around movement, live entertainment, or competitive games.',
        bestMatches: ['Aquarius', 'Libra', 'Leo'],
        intimacyTip: 'Share a secret aspiration you rarely voice to bridge romantic excitement into emotional trust.',
      },
      married: {
        headline: 'Passionate Renewal & Collaborative Triumph',
        overview: 'Your committed bond benefits from shared ambition and spontaneous romance. Channel your collective energy into a creative project or an impromptu romantic escape.',
        cosmicVibe: 'Devoted Spark & Fierce Loyalty',
        heartRating: 5,
        keyGuidance: 'Celebrate your partner’s independent victories as warmly as your shared milestones.',
        greenFlagOrFocus: 'Mutual vulnerability and laughing together over unexpected everyday quirks.',
        sacredAction: 'Surprise your partner with an unplanned evening sanctuary ritual or impromptu date.',
        bestMatches: ['Sagittarius', 'Gemini', 'Taurus'],
        intimacyTip: 'Physical touch combined with sincere verbal praise instantly melts lingering daily stresses.',
      },
    },
    taurus: {
      single: {
        headline: 'Sensual Magnetism & High Value Magnetism',
        overview: 'Venus envelops you in an irresistible aura of grounded elegance and sensual self-worth. You are attracting partners who appreciate beauty, stability, and genuine warmth.',
        cosmicVibe: 'Sensual, Luxuriant & Grounded',
        heartRating: 5,
        keyGuidance: 'Honor your high standards. The universe is aligning you with someone who cherishes your steadfast heart.',
        greenFlagOrFocus: 'Emotional consistency, punctuality, and someone who respects your personal boundaries.',
        sacredAction: 'Indulge in a luxurious lavender or rose bath; your self-love acts as a cosmic love magnet.',
        bestMatches: ['Virgo', 'Capricorn', 'Pisces'],
        intimacyTip: 'Let your body language convey relaxed ease—slow, deliberate conversations build irresistible intrigue.',
      },
      dating: {
        headline: 'Delicious Connections & Cultivating Trust',
        overview: 'Courtship moves at a sweet, deliberate tempo. Focus on sensory experiences—art galleries, botanical gardens, or sharing gourmet artisan meals together.',
        cosmicVibe: 'Slow Burn & Sweet Devotion',
        heartRating: 4,
        keyGuidance: 'Allow emotional intimacy to steep naturally without feeling pressured to rush milestone decisions.',
        greenFlagOrFocus: 'Someone who remembers the small details about your favorite foods, scents, and comfort rituals.',
        sacredAction: 'Cook a thoughtful homemade dinner or gift a beautiful botanical bloom.',
        bestMatches: ['Cancer', 'Scorpio', 'Virgo'],
        intimacyTip: 'Create an atmosphere of tactile comfort with soft lighting and calming ambient music on dates.',
      },
      married: {
        headline: 'Deep Physical Devotion & Home Sanctuary',
        overview: 'Your marital foundation radiates peace and enduring prosperity. Infuse your domestic sanctuary with shared culinary treats, cozy embraces, and heartfelt gratitude.',
        cosmicVibe: 'Unshakeable Harmony & Sacred Union',
        heartRating: 5,
        keyGuidance: 'Cultivate novelty within your treasured routines. A simple change of scenery rekindles deep passion.',
        greenFlagOrFocus: 'Effortless quiet companionship where silence feels deeply comforting rather than distant.',
        sacredAction: 'Massage each other’s shoulders with essential rose oils before bedtime.',
        bestMatches: ['Capricorn', 'Cancer', 'Pisces'],
        intimacyTip: 'Reaffirm your enduring commitment through warm, unhurried physical affection and gentle words.',
      },
    },
    gemini: {
      single: {
        headline: 'Sparkling Intellect & Synchronous Encounters',
        overview: 'Mercury amplifies your charm, curiosity, and quick wit. Serendipitous conversations in unexpected locations could spark an intriguing romantic connection.',
        cosmicVibe: 'Witty, Breezy & Flirtatious',
        heartRating: 4,
        keyGuidance: 'Engage with people who stimulate your mind first. Mental compatibility is your doorway to lasting affection.',
        greenFlagOrFocus: 'Someone who asks thought-provoking questions and introduces you to fascinating new ideas.',
        sacredAction: 'Visit a bookstore, quirky cafe, or cultural lecture to cross paths with like-minded souls.',
        bestMatches: ['Libra', 'Aquarius', 'Aries'],
        intimacyTip: 'Send a clever, humorous message that references a shared inside joke.',
      },
      dating: {
        headline: 'Lively Banter & Shared Exploration',
        overview: 'Dating is an exhilarating intellectual dance. Plan interactive dates where you can both converse freely, explore new neighborhoods, or sample eccentric culinary flights.',
        cosmicVibe: 'Dynamic Sparks & Mental Kinship',
        heartRating: 5,
        keyGuidance: 'Balance fast-paced humor with moments of calm, emotional vulnerability to deepen genuine connection.',
        greenFlagOrFocus: 'Effortless conversational flow where hours melt away without checking phones.',
        sacredAction: 'Exchange a favorite poem, song playlist, or memorable childhood story.',
        bestMatches: ['Leo', 'Libra', 'Sagittarius'],
        intimacyTip: 'Look deeply into their eyes during a quiet pause in conversation to let emotional depth land.',
      },
      married: {
        headline: 'Youthful Renewal & Playful Camaraderie',
        overview: 'Your marriage thrives when you keep curiosity alive. Treat your partner as your best friend and co-conspirator in lifelong learning and adventurous discovery.',
        cosmicVibe: 'Joyful Friendship & Fresh Perspectives',
        heartRating: 4,
        keyGuidance: 'Break out of conversational auto-pilot. Ask your spouse new questions about their evolving dreams.',
        greenFlagOrFocus: 'Spontaneous laughing fits and shared excitement over future travel or home aspirations.',
        sacredAction: 'Plan a mini road trip or an evening puzzle/board game night just for the two of you.',
        bestMatches: ['Aquarius', 'Aries', 'Libra'],
        intimacyTip: 'Leave a handwritten playful love note tucked into their wallet or morning notebook.',
      },
    },
    cancer: {
      single: {
        headline: 'Intuitive Radiance & Tender Protection',
        overview: 'The Moon heightens your emotional depth and empathic radiance. You are projecting a warm, nurturing frequency that attracts genuine, emotionally mature suitors.',
        cosmicVibe: 'Gentle, Magnetic & Soulful',
        heartRating: 5,
        keyGuidance: 'Keep your energetic boundaries clear while keeping your heart receptive to true kindness.',
        greenFlagOrFocus: 'A person who proves consistency with actions and creates emotional safety for your feelings.',
        sacredAction: 'Cleanse your heart chakra with moonstone and set intentions for reciprocated devotion.',
        bestMatches: ['Scorpio', 'Pisces', 'Taurus'],
        intimacyTip: 'Share a cherished memory or family recipe to invite reciprocal emotional depth.',
      },
      dating: {
        headline: 'Tender Vulnerability & Cozy Intimacy',
        overview: 'Romantic momentum deepens as you create cozy, intimate settings. Prioritize low-pressure dates like sunset walks, homemade picnics, or quiet acoustic cafes.',
        cosmicVibe: 'Sweet Resonance & Deepening Comfort',
        heartRating: 4,
        keyGuidance: 'Allow the other person to nurture you too; reciprocal care is the cornerstone of lasting love.',
        greenFlagOrFocus: 'Attentiveness to your comfort and genuine interest in meeting your inner circle.',
        sacredAction: 'Prepare a warm soothing tea or bake together in a relaxed atmosphere.',
        bestMatches: ['Virgo', 'Scorpio', 'Capricorn'],
        intimacyTip: 'Hold hands during quiet walks to establish grounding tactile reassurance.',
      },
      married: {
        headline: 'Sacred Nesting & Unconditional Devotion',
        overview: 'Your domestic sanctuary is blessed with emotional harmony. Celebrate the sacred fortress of love you have built together through heartfelt gratitude and warm closeness.',
        cosmicVibe: 'Soulbound Union & Emotional Haven',
        heartRating: 5,
        keyGuidance: 'Express appreciation for the emotional anchor your partner provides in your daily journey.',
        greenFlagOrFocus: 'Deep emotional attunement where words are unnecessary to understand each other’s heart.',
        sacredAction: 'Create a candlelit dinner at home with nostalgic photos and favorite shared melodies.',
        bestMatches: ['Pisces', 'Taurus', 'Scorpio'],
        intimacyTip: 'Share a long, uninterrupted embrace before starting or ending the day.',
      },
    },
    leo: {
      single: {
        headline: 'Regal Magnetism & Golden Heart Warmth',
        overview: 'The Sun illuminates your royal charm. Your radiant warmth and natural generosity light up every room, effortlessly drawing admirers who appreciate your luminous spirit.',
        cosmicVibe: 'Dazzling, Generous & Sovereign',
        heartRating: 5,
        keyGuidance: 'Choose a partner who adores your brilliance without feeling shadowed by your light.',
        greenFlagOrFocus: 'Someone who offers genuine compliments and takes pride in seeing you shine.',
        sacredAction: 'Wear gold jewelry or citrine to amplify your solar confidence and romantic radiance.',
        bestMatches: ['Aries', 'Sagittarius', 'Libra'],
        intimacyTip: 'Showcase your playful, affectionate humor; true warmth is always your most captivating quality.',
      },
      dating: {
        headline: 'Grand Gestures & Romantic Glamour',
        overview: 'Your courtship is cinematic and full of celebration. Plan dates with ambiance—live music, elegant dressing up, and spirited toasts to life’s beauty.',
        cosmicVibe: 'Celebratory, Romantic & Expressive',
        heartRating: 4,
        keyGuidance: 'Make sure appreciation is a two-way street. Celebrate your date’s unique talents and achievements.',
        greenFlagOrFocus: 'A date who makes you feel cherished, respected, and fully seen in your creative authenticity.',
        sacredAction: 'Dress in your favorite bold attire and take radiant photos together.',
        bestMatches: ['Gemini', 'Aries', 'Sagittarius'],
        intimacyTip: 'Whisper sincere admiration into their ear during a special shared moment.',
      },
      married: {
        headline: 'Loyal Queens & Kings of the Heart',
        overview: 'Your union thrives on mutual loyalty and proud devotion. Honor the shared kingdom you’ve built by rekindling the passionate courtship that first united your souls.',
        cosmicVibe: 'Majestic Union & Enduring Passion',
        heartRating: 5,
        keyGuidance: 'Keep romance grand even in routine moments. Small unexpected declarations keep the fire roaring.',
        greenFlagOrFocus: 'Standing proudly by each other’s side in public and private with unwavering fidelity.',
        sacredAction: 'Plan a celebratory weekend getaway or an upscale date night just for the two of you.',
        bestMatches: ['Libra', 'Aries', 'Gemini'],
        intimacyTip: 'Look into your partner’s eyes and declare your renewed romantic allegiance with passionate clarity.',
      },
    },
    virgo: {
      single: {
        headline: 'Pure Discernment & Wholesome Allure',
        overview: 'Mercury gives you clear discernment and refined grace. You are attracting high-caliber suitors who admire your competence, gentle integrity, and perceptive intelligence.',
        cosmicVibe: 'Refined, Perceptive & Wholesome',
        heartRating: 4,
        keyGuidance: 'Release unrealistic perfectionist benchmarks; allow human quirks and genuine authenticity to blossom.',
        greenFlagOrFocus: 'A partner who is organized, emotionally accountable, and attentive to subtle details.',
        sacredAction: 'Ground yourself in nature or write a clear list of non-negotiable spiritual values in a partner.',
        bestMatches: ['Taurus', 'Capricorn', 'Cancer'],
        intimacyTip: 'Offer a thoughtful insight or sincere practical compliment that shows you notice their unique essence.',
      },
      dating: {
        headline: 'Thoughtful Gestures & Quiet Harmony',
        overview: 'Your dating connections flourish through acts of service and meaningful dialogues. Share quiet walks, wellness retreats, or collaborative DIY cooking experiences.',
        cosmicVibe: 'Thoughtful Chemistry & Calm Bonding',
        heartRating: 4,
        keyGuidance: 'Express what you appreciate out loud rather than keeping observations locked in your analytical mind.',
        greenFlagOrFocus: 'Punctuality, respectful listening, and someone who honors your personal rhythm.',
        sacredAction: 'Brew an herbal wellness infusion and share a tranquil conversation without digital distractions.',
        bestMatches: ['Scorpio', 'Taurus', 'Pisces'],
        intimacyTip: 'Gently tuck their hair behind their ear or offer a subtle reassuring hand squeeze.',
      },
      married: {
        headline: 'Devoted Partnership & Sacred Everyday Care',
        overview: 'Your committed partnership is a masterpiece of daily devotion and quiet reliability. Celebrate the beauty of your shared rhythm and mutual supportive foundation.',
        cosmicVibe: 'Enduring Devotion & Holistic Alignment',
        heartRating: 5,
        keyGuidance: 'Focus on what is right rather than what needs fixing. Gratitude softens all analytical edges.',
        greenFlagOrFocus: 'Seamless teamwork in managing home goals while carving out sacred romantic breathers.',
        sacredAction: 'Prepare their favorite morning beverage with an affectionate note placed beside it.',
        bestMatches: ['Capricorn', 'Taurus', 'Cancer'],
        intimacyTip: 'Offer an unprompted gentle hand or foot massage to alleviate their daily physical tension.',
      },
    },
    libra: {
      single: {
        headline: 'Harmonious Grace & Venusian Charm',
        overview: 'Venus blesses you with effortless romantic allure and exquisite social grace. Your balanced energy and diplomatic charm attract suitors seeking genuine aesthetic and emotional harmony.',
        cosmicVibe: 'Graceful, Alluring & Poetic',
        heartRating: 5,
        keyGuidance: 'Do not compromise your core needs just to maintain surface peace. State your desires with clear elegance.',
        greenFlagOrFocus: 'Someone who values equality, reciprocity, and treats everyone around them with gracious courtesy.',
        sacredAction: 'Surround yourself with fresh flowers and wear rose quartz to magnetize soulmate energy.',
        bestMatches: ['Gemini', 'Aquarius', 'Leo'],
        intimacyTip: 'Engage with gentle, charming smiles and attentive questions that invite them to open up.',
      },
      dating: {
        headline: 'Romantic Symmetry & Cultural Escapes',
        overview: 'Dates feel like poetry when accompanied by art, music, and balanced conversation. Explore galleries, upscale cafes, or open-air musical performances.',
        cosmicVibe: 'Sweet Symmetry & Aesthetic Connection',
        heartRating: 5,
        keyGuidance: 'Share what you truly think rather than always mirroring your date’s preferences.',
        greenFlagOrFocus: 'Reciprocal planning where both parties enthusiastically contribute creative date ideas.',
        sacredAction: 'Curate a romantic acoustic playlist and share it with your love interest.',
        bestMatches: ['Sagittarius', 'Gemini', 'Aries'],
        intimacyTip: 'Compliment their style and aesthetic choices with genuine, articulate appreciation.',
      },
      married: {
        headline: 'Balanced Sacred Union & Lifelong Companionship',
        overview: 'Your marriage is a testament to true partnership and shared beauty. Harmonize any lingering imbalances through affectionate dialogue and intentional romantic date nights.',
        cosmicVibe: 'Harmonious Oneness & Deep Loyalty',
        heartRating: 5,
        keyGuidance: 'Address subtle grievances early with gentle kindness before they accumulate into emotional distance.',
        greenFlagOrFocus: 'Shared laughter and finding mutual delight in creating a peaceful, beautiful lifestyle together.',
        sacredAction: 'Dedicate one evening this week entirely to candlelit dining and heartfelt reminiscence.',
        bestMatches: ['Aquarius', 'Leo', 'Gemini'],
        intimacyTip: 'Hold each other close and slow dance in the living room to your original wedding or theme song.',
      },
    },
    scorpio: {
      single: {
        headline: 'Mesmerizing Depth & Magnetic Mystery',
        overview: 'Pluto and Mars endow you with an hypnotic, penetrative aura. Superficial connections will not satisfy you—your soul is broadcasting a frequency for transformative, soul-deep romance.',
        cosmicVibe: 'Intense, Enigmatic & Transformational',
        heartRating: 5,
        keyGuidance: 'Trust your intuitive radar. If something feels off, honor it; if it feels sacred, let your walls gently soften.',
        greenFlagOrFocus: 'Absolute emotional transparency and a partner who isn’t intimidated by your intensity.',
        sacredAction: 'Meditate with black obsidian or ruby to protect your sacred energy while remaining open.',
        bestMatches: ['Cancer', 'Pisces', 'Virgo'],
        intimacyTip: 'Maintain deep, unwavering eye contact during conversation; your gaze speaks volumes.',
      },
      dating: {
        headline: 'Passionate Exploration & Soul-Baring Truths',
        overview: 'Your courtship avoids small talk in favor of profound disclosures and electric chemistry. Meet in dimly lit, intimate venues where deep secrets can be shared safely.',
        cosmicVibe: 'Electric Chemistry & Deep Resonance',
        heartRating: 4,
        keyGuidance: 'Pace your revelations and remember that vulnerability is an act of sovereign bravery.',
        greenFlagOrFocus: 'Consistent honesty and someone who keeps your confidences strictly sacred.',
        sacredAction: 'Share a personal life philosophy or transformative experience that shaped your soul.',
        bestMatches: ['Capricorn', 'Cancer', 'Taurus'],
        intimacyTip: 'A slow, intentional touch on the forearm can transmit profound unspoken emotional resonance.',
      },
      married: {
        headline: 'Alchemical Devotion & Unbreakable Loyalty',
        overview: 'Your marital bond is a sacred cauldron of mutual transformation and absolute loyalty. Recommit to deep emotional and physical intimacy that rejuvenates your union.',
        cosmicVibe: 'Soul Fusion & Sacred Fidelity',
        heartRating: 5,
        keyGuidance: 'Release lingering grudges completely; forgiveness is the key that unlocks passionate rebirth.',
        greenFlagOrFocus: 'Unshakable mutual defense and total trust that weathers every external storm.',
        sacredAction: 'Spend an evening with zero technology, talking in the dark about your deepest spiritual dreams.',
        bestMatches: ['Pisces', 'Cancer', 'Virgo'],
        intimacyTip: 'Express unfiltered appreciation for the fierce loyalty your partner demonstrates each day.',
      },
    },
    sagittarius: {
      single: {
        headline: 'Adventurous Spirit & Jovial Allure',
        overview: 'Jupiter fills you with expansive joy, humor, and boundless optimism. Your infectious zest for life and philosophic worldview attract free-spirited suitors from all walks of life.',
        cosmicVibe: 'Expansive, Joyful & Uninhibited',
        heartRating: 5,
        keyGuidance: 'Look for a co-traveler who shares your appetite for truth, wisdom, and laughter.',
        greenFlagOrFocus: 'Someone who respects your need for personal freedom and possesses a rich sense of humor.',
        sacredAction: 'Take a spontaneous day trip or explore an unfamiliar part of town with an open heart.',
        bestMatches: ['Aries', 'Leo', 'Libra'],
        intimacyTip: 'Share a hilarious travel anecdote or philosophical belief that reveals your spirited core.',
      },
      dating: {
        headline: 'Exciting Horizons & Mutual Philosophy',
        overview: 'Dating is an exhilarating journey into new territories. Choose dynamic dates: outdoor hikes, international food festivals, or stargazing under open skies.',
        cosmicVibe: 'Spontaneous Exploration & Shared Laughter',
        heartRating: 4,
        keyGuidance: 'Anchor your spontaneity with present-moment attentiveness to your date’s feelings.',
        greenFlagOrFocus: 'Willingness to try new experiences with enthusiasm and good-natured adaptability.',
        sacredAction: 'Gift a thought-provoking book or invite them to a lively cultural gathering.',
        bestMatches: ['Aquarius', 'Aries', 'Gemini'],
        intimacyTip: 'Laugh freely together; shared humor is your fastest pathway to genuine romantic chemistry.',
      },
      married: {
        headline: 'Lifelong Co-Adventurers & Philosophical Union',
        overview: 'Your marriage thrives when you continue to explore the world and expand your minds together. Keep the horizon wide with collaborative travels and optimistic dreams.',
        cosmicVibe: 'Boundless Friendship & Shared Vision',
        heartRating: 5,
        keyGuidance: 'Keep everyday domestic life from feeling stagnant by scheduling recurring novelty and discovery.',
        greenFlagOrFocus: 'Encouraging each other to pursue personal passions without fear of jealousy or confinement.',
        sacredAction: 'Book tickets for a future expedition or attend a live cultural workshop together.',
        bestMatches: ['Leo', 'Aries', 'Libra'],
        intimacyTip: 'Reaffirm how much joy and laughter your partner brings into your daily existence.',
      },
    },
    capricorn: {
      single: {
        headline: 'Steadfast Nobility & High-Status Allure',
        overview: 'Saturn endows you with quiet authority, deep reliability, and timeless maturity. You are magnetizing suitors who value character, long-term integrity, and lasting legacy.',
        cosmicVibe: 'Dignified, Ambitious & Enduring',
        heartRating: 4,
        keyGuidance: 'Allow your dry, witty humor and tender heart to peek through your reserved exterior.',
        greenFlagOrFocus: 'Emotional maturity, solid ambition, and respect for your hard-earned time and goals.',
        sacredAction: 'Wear grounding garnet or onyx to project steady, unshakeable self-assurance.',
        bestMatches: ['Taurus', 'Virgo', 'Scorpio'],
        intimacyTip: 'Show appreciation for a suitor’s dependability and let your softer, affectionate side shine.',
      },
      dating: {
        headline: 'Building Solid Ground & Meaningful Milestones',
        overview: 'Your courtship progresses with deliberate care and mutual respect. Choose dates with heritage and substance: historic architecture, fine jazz, or serene nature vistas.',
        cosmicVibe: 'Substantive Bonding & Mutual Respect',
        heartRating: 4,
        keyGuidance: 'Don’t treat romance like an interview; relax into the present moment and enjoy the unscripted flow.',
        greenFlagOrFocus: 'Honoring commitments without excuses and showing genuine respect for family and career.',
        sacredAction: 'Share your long-term creative dreams and ask about their life vision in return.',
        bestMatches: ['Pisces', 'Taurus', 'Cancer'],
        intimacyTip: 'Offer a warm, steady embrace that lets your date feel completely secure in your presence.',
      },
      married: {
        headline: 'Enduring Dynasty & Sacred Architectural Union',
        overview: 'Your marriage is a rock-solid partnership built to withstand any storm. Celebrate the tangible legacy, stability, and deep mutual trust you have cultivated together.',
        cosmicVibe: 'Unshakable Loyalty & Enduring Devotion',
        heartRating: 5,
        keyGuidance: 'Remember to nurture romantic play alongside practical life duties and financial planning.',
        greenFlagOrFocus: 'Flawless teamwork in crisis and quiet pride in the life and legacy you are constructing.',
        sacredAction: 'Schedule a dedicated date night where all talk of chores, work, and logistics is forbidden.',
        bestMatches: ['Virgo', 'Taurus', 'Scorpio'],
        intimacyTip: 'Express heartfelt verbal gratitude for how hard your spouse works for your collective future.',
      },
    },
    aquarius: {
      single: {
        headline: 'Visionary Charm & Electric Individuality',
        overview: 'Uranus and Saturn give you an avant-garde charisma and humanitarian brilliance. You are attracting suitors who are fascinated by your unique perspectives and independent spirit.',
        cosmicVibe: 'Innovative, Magnetic & Unconventional',
        heartRating: 5,
        keyGuidance: 'Stay unapologetically yourself. The right person will love your quirks, not tolerate them.',
        greenFlagOrFocus: 'Someone who champions your humanitarian ideals and gives you room to breathe.',
        sacredAction: 'Wear amethyst or celestial turquoise to enhance your progressive aura.',
        bestMatches: ['Gemini', 'Libra', 'Sagittarius'],
        intimacyTip: 'Engage in a debate on future technology or cosmic mysteries—intellectual sparks ignite passion.',
      },
      dating: {
        headline: 'Electric Camaraderie & Uncharted Dynamics',
        overview: 'Dating is an exciting meeting of minds and unusual adventures. Choose unconventional venues: science museums, indie film screenings, or stargazing astronomy nights.',
        cosmicVibe: 'Exciting Freedom & Soul Connection',
        heartRating: 4,
        keyGuidance: 'Bridge your intellectual banter with emotional warmth so your date feels deeply chosen.',
        greenFlagOrFocus: 'Unconventional date ideas and someone who values your independent circle of friends.',
        sacredAction: 'Introduce them to your favorite community cause or visionary indie project.',
        bestMatches: ['Aries', 'Gemini', 'Libra'],
        intimacyTip: 'Share an idiosyncratic childhood memory that nobody else knows about you.',
      },
      married: {
        headline: 'Soul Camaraderie & Progressive Partnership',
        overview: 'Your marriage is a modern partnership of equals, deep friendship, and shared humanitarian ideals. Keep your connection vibrant through collaborative growth and creative freedom.',
        cosmicVibe: 'Equal Partnership & Shared Vision',
        heartRating: 5,
        keyGuidance: 'Continually reinvent your relationship so it remains dynamic, fresh, and forward-looking.',
        greenFlagOrFocus: 'Mutual support for each other’s personal evolutions without judgment.',
        sacredAction: 'Collaborate on a community initiative or visionary household innovation together.',
        bestMatches: ['Libra', 'Gemini', 'Sagittarius'],
        intimacyTip: 'Surprise your partner with a quirky, personalized gift that honors an obscure shared joke.',
      },
    },
    pisces: {
      single: {
        headline: 'Dreamy Mysticism & Ethereal Romance',
        overview: 'Neptune and Jupiter bathe you in an aura of poetic compassion and mystical magnetism. You are attracting souls who crave genuine emotional depth, artistic beauty, and spiritual romance.',
        cosmicVibe: 'Soulful, Dreamy & Compassionate',
        heartRating: 5,
        keyGuidance: 'Maintain healthy romantic boundaries; fall in love with who they are today, not just their potential.',
        greenFlagOrFocus: 'Kindness toward animals, gentle communication, and emotional consistency.',
        sacredAction: 'Meditate near water or with aquamarine crystals to tune into soulmate synchronicities.',
        bestMatches: ['Cancer', 'Scorpio', 'Taurus'],
        intimacyTip: 'Express your feelings through music, art, or a poetic compliment that touches the heart.',
      },
      dating: {
        headline: 'Fairy Tale Romance & Telepathic Resonance',
        overview: 'Your courtship is steeped in romantic magic and subtle intuition. Plan dates by the water, visits to live orchestral concerts, or candlelit acoustic poetry nights.',
        cosmicVibe: 'Enchanted Bonding & Tender Connection',
        heartRating: 5,
        keyGuidance: 'Communicate your practical needs clearly instead of assuming your partner can telepathically read them.',
        greenFlagOrFocus: 'Emotional vulnerability, deep compassion, and sharing your love of music and art.',
        sacredAction: 'Create a collaborative art piece or share your favorite mystical dreams together.',
        bestMatches: ['Capricorn', 'Scorpio', 'Cancer'],
        intimacyTip: 'Hold their hand and listen deeply to their words with undivided, compassionate presence.',
      },
      married: {
        headline: 'Sacred Soulmates & Transcendent Devotion',
        overview: 'Your marriage is a sanctuary of unconditional love and spiritual unity. Celebrate the telepathic bond and profound empathy that binds your souls across time and space.',
        cosmicVibe: 'Transcendent Love & Soul Union',
        heartRating: 5,
        keyGuidance: 'Ground your romantic dreams in daily practical care and joyful mutual rituals.',
        greenFlagOrFocus: 'Telepathic understanding where you finish each other’s sentences and sense each other’s mood.',
        sacredAction: 'Take a serene sunset walk along a beach or tranquil lake and express your soulmate vows anew.',
        bestMatches: ['Cancer', 'Taurus', 'Scorpio'],
        intimacyTip: 'Offer a long, silent, heart-to-heart embrace that recalibrates your energetic resonance together.',
      },
    },
  };

  const signData = forecasts[signName] || forecasts.aries;
  const statusData = signData[status];

  const categoryTitles: Record<RelationshipStatus, string> = {
    single: 'Single & Manifesting',
    dating: 'Dating & Courting',
    married: 'Married & Committed',
  };

  return {
    title: categoryTitles[status],
    status,
    ...statusData,
  };
};
